# Generated by Django 4.0 on 2021-12-29 14:34

from django.db import migrations, models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[post.validators.validate_file_size]),
        ),
    ]
