# Generated by Django 4.0 on 2021-12-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='re_published',
            field=models.BooleanField(default=False),
        ),
    ]
