# Generated by Django 4.0 on 2022-01-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_re_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary(Will be displayed on the landing-page)'),
        ),
    ]
