# Generated by Django 4.0 on 2022-01-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=300, verbose_name='Summary(Will be displayed on the landing page)'),
        ),
    ]
