# Generated by Django 4.0 on 2022-01-03 00:03

from django.db import migrations, models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[post.validators.validate_file_size]),
        ),
    ]
