# Generated by Django 4.0 on 2022-01-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='re_published',
            field=models.BooleanField(default=False, verbose_name='Re-published'),
        ),
    ]
