# Generated by Django 4.0 on 2022-01-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_avatar'),
        ('post', '0010_alter_post_published_alter_post_re_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='Deleted User', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.customuser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=12000),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=300, verbose_name='Summary(Card description on landing page)'),
        ),
    ]
