# Generated by Django 4.0 on 2022-01-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Technology', 'Technology'), ('Environment', 'Environment'), ('Aviation', 'Aviation'), ('Civil', 'Civil'), ('Healthcare', 'Healthcare'), ('Bio-Engineering', 'Bio-Engineering'), ('Engineering', 'Engineering')], default='', max_length=50),
        ),
    ]
