# Generated by Django 4.0 on 2022-01-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clicks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
