# Generated by Django 4.0 on 2021-12-31 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('sent_date', models.DateField(blank=True, default=datetime.date)),
                ('recipient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_notification', to='account.customuser')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_notification', to='account.customuser')),
            ],
        ),
    ]
