# Generated by Django 4.0 on 2022-01-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
