# Generated by Django 4.0 on 2022-01-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notified',
        ),
    ]
