# Generated by Django 4.0 on 2022-01-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_re_published'),
        ('notification', '0006_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.post'),
        ),
    ]
